import React, { useState } from "react";
import { Space, Input, Select, Switch, Row, Col, Button } from "antd";
import { PostParamsType } from "../../types/post.type";
const { Search } = Input;
export type PostFiltersState = Omit<PostParamsType, "page" | "pageSize">;

type PostFiltersProps = {
  onFilterChange: (filters: PostFiltersState) => void;
};
const PostFilters: React.FC<PostFiltersProps> = ({ onFilterChange }) => {
  const [filters, setFilters] = useState<PostFiltersState>({
    search: undefined,
    status: undefined,
    generatedBy: undefined,
    isFeatured: false,
  });
  const handleChange = (key: keyof PostFiltersState, value: any) => {
    const updated = { ...filters, [key]: value };
    setFilters(updated);
    onFilterChange?.(updated);
  };
  const clearAllFilters = () => {
    const clearedFilters: PostFiltersState = {
      search: undefined,
      status: undefined,
      generatedBy: undefined,
      isFeatured: false,
    };
    setFilters(clearedFilters);
    onFilterChange?.(clearedFilters);
  };
  return (
    <Row
      gutter={[16, 16]}
      style={{
        marginBottom: 20,
        marginTop: 20,
        padding: 20,
        borderRadius: 10,
        boxShadow: "0 5px 15px 5px #f5f5f5",
      }}
    >
      {/* Search */}
      <Col xs={24} sm={12} lg={6}>
        <Search
          value={filters.search}
          placeholder="Tìm kiếm bài viết"
          allowClear
          onSearch={(value) => handleChange("search", value)}
        />
      </Col>

      {/* Status */}
      <Col xs={24} sm={12} lg={6}>
        <Select
          placeholder="Chọn trạng thái"
          allowClear
          style={{ width: "100%" }}
          value={filters.status}
          onChange={(value) => handleChange("status", value)}
          options={[
            { label: "Bản nháp", value: "draft" },
            { label: "Đã xuất bản", value: "published" },
            { label: "Lịch trình", value: "scheduled" },
          ]}
        />
      </Col>

      {/* Generated By */}
      <Col xs={24} sm={12} lg={6}>
        <Select
          placeholder="Generated By"
          allowClear
          value={filters.generatedBy}
          style={{ width: "100%" }}
          onChange={(value) => handleChange("generatedBy", value)}
          options={[
            { label: "Người", value: "human" },
            { label: "AI", value: "ai" },
            { label: "Hybrid", value: "hybrid" },
          ]}
        />
      </Col>

      {/* Featured */}
      <Col xs={24} sm={12} lg={4}>
        <Space>
          <span>Nổi bật:</span>
          <Switch
            value={filters.isFeatured}
            onChange={(checked) =>
              handleChange("isFeatured", checked ? true : undefined)
            }
          />
        </Space>
      </Col>

      {/* Clear All - xuống hàng, căn phải */}
      <Col xs={24} sm={12} lg={2}>
        <Button type="primary" onClick={clearAllFilters} size="small">
          Xóa tất cả
        </Button>
      </Col>
    </Row>
  );
};

export default PostFilters;
