version: "3"
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build: .
    container_name: server
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
